// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeLastScan():Promise<Array<models.Recommendation>>;

export function CanContinueAnalyze():Promise<boolean>;

export function Clean(arg1:models.CleanRequest):Promise<models.CleanSummary>;

export function ContinueAnalyzeLastScan():Promise<Array<models.Recommendation>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetLLMDebugInfo():Promise<models.LLMDebugInfo>;

export function GetTokenStats():Promise<models.TokenStats>;

export function IsElevated():Promise<boolean>;

export function RequestElevation():Promise<void>;

export function SaveConfig(arg1:models.AppConfig):Promise<void>;

export function ScanDrive(arg1:string):Promise<models.ScanResult>;
