// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLastScan() {
  return window['go']['main']['App']['AnalyzeLastScan']();
}

export function CanContinueAnalyze() {
  return window['go']['main']['App']['CanContinueAnalyze']();
}

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function ContinueAnalyzeLastScan() {
  return window['go']['main']['App']['ContinueAnalyzeLastScan']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLLMDebugInfo() {
  return window['go']['main']['App']['GetLLMDebugInfo']();
}

export function GetTokenStats() {
  return window['go']['main']['App']['GetTokenStats']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanDrive(arg1) {
  return window['go']['main']['App']['ScanDrive'](arg1);
}
